# HackerRank Python Practice

### Say "Hello, World!" 

In [1]:
print("Hello, World!")

Hello, World!


### If-Else

In [4]:
N = int(input())
if N%2==1:
    print("Weird")
else:
    if N>=2 and N<=5:
        print("Not Weird")
    elif N>=6 and N<=20:
        print("Weird")
    elif N>=20:
        print("Not Weird")

7
Weird


### Division
https://www.hackerrank.com/challenges/python-division/problem

In [2]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    
    print(int(a/b))
    print(a/b)

4
3
1
1.3333333333333333


### Loops
https://www.hackerrank.com/challenges/python-loops/problem?h_r=next-challenge&h_v=zen

In [3]:
if __name__ == '__main__':
    n = int(input())
    if n>=1 and n<=20:
        for i in range(n):
            print(i*i)

5
0
1
4
9
16


### Functions
https://www.hackerrank.com/challenges/write-a-function/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [4]:
def is_leap(year):
    leap = False
    if year%100 == 0:
        if year %400 == 0:
            leap = True
    else:
        if year % 4 == 0:
            leap = True
    return leap

year = int(input())
print(is_leap(year))

1990
False


### Print
https://www.hackerrank.com/challenges/python-print/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [5]:
if __name__ == '__main__':
    n = int(input())
    out = ''
    for i in range(1, n+1):
        out += str(i)
    print(out)

3
123


### Shape and Reshape
https://www.hackerrank.com/challenges/np-shape-reshape/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

##### shape 
change_array.shape = (3, 2)

##### reshape
The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

'numpy.reshape(my_array,(3,2))'

In [7]:
import numpy

inputArray = numpy.array([int(n) for n in input().split()])
print (numpy.reshape(inputArray, (3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten
https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [42]:
import numpy

N,M = [int(t) for t in input().split()]
array = []
for i in range(N):
    array.append([int(t) for t in input().split()])

print(numpy.array(array).transpose())
print(numpy.array(array).flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate 
https://www.hackerrank.com/challenges/np-concatenate/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [44]:
import numpy

N, M, P = [int(t) for t in input().split()]

first = []
for i in range(N):
    first.append([int(t) for t in input().split()])
second = []
for i in range(M):
    second.append([int(t) for t in input().split()])

print(numpy.concatenate((numpy.array(first), numpy.array(second)), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeros and Ones
https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?h_r=next-challenge&h_v=zen